### PR TITLE
add "help" command

### LINKED ISSUE #787: cli: add 'help' command
add a `help` command with the following spec:

```bash
popper help [subcommand]
```

When `[subcommand]` is not given, it is equivalent to the current `popper --help`. When the `[subcommand]` argument is given, it is equivalent to `popper subcommand --help`.

For this, the help message doesn't have to be recreated, but instead we can invoke Click's [`get_help()`](http://click.palletsprojects.com/en/7.x/api/#click.Command.get_help) function of each subcommand.

### PR DESCRIPTION
**Pull request by fsr313**
fixes #787

### CODE REVIEW

**Comment by JayjeetAtGithub** [comment]
Hi @fsr313. Thanks a lot for working on this. Can you please add unit tests for this feature? You can look at the [`popper version`](https://github.com/getpopper/popper/blob/master/src/test/test_cmd_version.py) tests as a reference.

**Comment by fsr313** [comment]
yes can do

**Comment by fsr313** [comment]
@JayjeetAtGithub may I get some help understanding why Travis failing the checks?
This is the log where the check fails
```
$ popper run
ERROR: Secret DOCKER_USERNAME not defined
The command "popper run" exited with 1.
```

**Comment by ivotron** [comment]
thanks @fsr313, and apologies for that terrible contributor experience. This is due to the way Travis deals with secrets (see #851). I see that tests are passing fine, so I'll merge as that error doesn't have to do with your changes.

**Pull request merged**
