### PR TITLE
WIP: singularity run options

### PR DESCRIPTION
**Pull request by Jswig**
Created PR from feature-specific branch as requested.

Allows any options available to `singularity run` to be passed to the Singularity runner in a step's `options`.
Updated documentation to reflect this feature.

### CODE REVIEW

**Comment by ivotron** [comment]
hey Anders, regarding the error. I moved the implementation of this to the `_get_container_options` function:

```diff
diff --git a/src/popper/runner_host.py b/src/popper/runner_host.py
index 241a6526..f0b65b2d 100644
--- a/src/popper/runner_host.py
+++ b/src/popper/runner_host.py
@@ -481,7 +481,7 @@ class SingularityRunner(StepRunner):
         )
         os.makedirs(self._singularity_cache, exist_ok=True)

-    def _get_container_options(self):
+    def _get_container_options(self, step):
         container_args = {
             "userns": True,
             "pwd": "/workspace",
@@ -498,6 +498,19 @@ class SingularityRunner(StepRunner):
             else:
                 options.append(pu.key_value_to_flag(k, v))

+        # options for step given in workflow definition
+        step_options = []  # step-specific configuration
+        for k, v in step.options.items():
+            if isinstance(v, list):
+                flag = f"-{k}" if len(k) == 1 else f"--{k}"
+                step_options.append(flag)
+                for item in v.items():
+                    step_options.append(item)
+            else:
+                step_options.append(pu.key_value_to_flag(k, v))
+        step_options = " ".join(step_options).split(" ")
+        options = options + step_options
+
         options = " ".join(options).split(" ")
         log.debug(f"container options: {options}\n")

@@ -545,18 +558,7 @@ class SingularityRunner(StepRunner):
         if self._config.dry_run:
             return 0

-        options = self._get_container_options()
-        step_options = []  # step-specific configuration
-        for k, v in step.options.items():
-            if isinstance(v, list):
-                flag = f"-{k}" if len(k) == 1 else f"--{k}"
-                step_options.append(flag)
-                for item in v.items():
-                    step_options.append(item)
-            else:
-                step_options.append(pu.key_value_to_flag(k, v))
-        step_options = " ".join(step_options).split(" ")
-        options = options + step_options
+        options = self._get_container_options(step)
```

The above allows to see in debug mode the list of arguments that are being passed to the engine. So this workflow:

```yaml
steps:

- uses: "docker://alpine:3.12"
  args: ["echo", "hello"]
```

ran in debug mode:

```bash
popper run -e singularity -d -f wf.yml
```

shows the following:

```
DEBUG: container options: ['--userns', '--pwd', '/workspace', '--bind', '/home/ivotron/tmp:/workspace', '']
```

So it seems that the problem is that empty argument being passed as an option

**Comment by ivotron** [comment]
hey @Jswig, any updates on this?

**Comment by Jswig** [comment]
> 
> 
> hey @Jswig, any updates on this?

Forgot about this, got really absorbed on the R project. Getting back on this tomorrow!

**Comment by ivotron** [comment]
closing this for now, please re-open if needed 🙏

**Pull request closed without merging**
